//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionHeart.BusinessLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LionHeart.BusinessLogic.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записи товаров найдены.
        /// </summary>
        internal static string BasketEntriesFound {
            get {
                return ResourceManager.GetString("BasketEntriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записи товаров не найдены.
        /// </summary>
        internal static string BasketEntriesNotFound {
            get {
                return ResourceManager.GetString("BasketEntriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары не были удалены из корзины.
        /// </summary>
        internal static string BasketEntriesNotRemoved {
            get {
                return ResourceManager.GetString("BasketEntriesNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар добавлен в корзину.
        /// </summary>
        internal static string BasketEntryCreated {
            get {
                return ResourceManager.GetString("BasketEntryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар удален из корзины.
        /// </summary>
        internal static string BasketEntryDeleted {
            get {
                return ResourceManager.GetString("BasketEntryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар найден в корзине.
        /// </summary>
        internal static string BasketEntryFound {
            get {
                return ResourceManager.GetString("BasketEntryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не добавлен в корзину.
        /// </summary>
        internal static string BasketEntryNotCreated {
            get {
                return ResourceManager.GetString("BasketEntryNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не удален из корзины.
        /// </summary>
        internal static string BasketEntryNotDeleted {
            get {
                return ResourceManager.GetString("BasketEntryNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар не найден в корзине.
        /// </summary>
        internal static string BasketEntryNotFound {
            get {
                return ResourceManager.GetString("BasketEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар в корзине не обновлен.
        /// </summary>
        internal static string BasketEntryNotUpdated {
            get {
                return ResourceManager.GetString("BasketEntryNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар в корзине обновлен.
        /// </summary>
        internal static string BasketEntryUpdated {
            get {
                return ResourceManager.GetString("BasketEntryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категории не были найдены.
        /// </summary>
        internal static string CategoriesNotFound {
            get {
                return ResourceManager.GetString("CategoriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория не была создана.
        /// </summary>
        internal static string CategoryNotCreated {
            get {
                return ResourceManager.GetString("CategoryNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория не была найдена.
        /// </summary>
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория не была удалена.
        /// </summary>
        internal static string CategoryNotRemoved {
            get {
                return ResourceManager.GetString("CategoryNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория не была обновлена.
        /// </summary>
        internal static string CategoryNotUpdated {
            get {
                return ResourceManager.GetString("CategoryNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания не была найдена.
        /// </summary>
        internal static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исключение: .
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт не был добавлен в избранное.
        /// </summary>
        internal static string FavoriteProductNotCreated {
            get {
                return ResourceManager.GetString("FavoriteProductNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт в избранном не был найден .
        /// </summary>
        internal static string FavoriteProductNotFound {
            get {
                return ResourceManager.GetString("FavoriteProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт не был удален из избранного.
        /// </summary>
        internal static string FavoriteProductNotRemoved {
            get {
                return ResourceManager.GetString("FavoriteProductNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукты в избранном не были найдены.
        /// </summary>
        internal static string FavoriteProductsNotFound {
            get {
                return ResourceManager.GetString("FavoriteProductsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзыв не был создан.
        /// </summary>
        internal static string FeedbackNotCreated {
            get {
                return ResourceManager.GetString("FeedbackNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзыв не был найден.
        /// </summary>
        internal static string FeedbackNotFound {
            get {
                return ResourceManager.GetString("FeedbackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзыв не был удален.
        /// </summary>
        internal static string FeedbackNotRemoved {
            get {
                return ResourceManager.GetString("FeedbackNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы не были найдены.
        /// </summary>
        internal static string FeedbacksNotFound {
            get {
                return ResourceManager.GetString("FeedbacksNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переданный файл не является картинкой.
        /// </summary>
        internal static string FileNotImage {
            get {
                return ResourceManager.GetString("FileNotImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картинка не была добавлена.
        /// </summary>
        internal static string ImageNotCreated {
            get {
                return ResourceManager.GetString("ImageNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя проблема сервера.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление не было создано.
        /// </summary>
        internal static string NotificationNotCreated {
            get {
                return ResourceManager.GetString("NotificationNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление не было найдено.
        /// </summary>
        internal static string NotificationNotFound {
            get {
                return ResourceManager.GetString("NotificationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомление не было удалено.
        /// </summary>
        internal static string NotificationNotRemoved {
            get {
                return ResourceManager.GetString("NotificationNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомления не были созданы.
        /// </summary>
        internal static string NotificationsNotCreated {
            get {
                return ResourceManager.GetString("NotificationsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомления не найдены.
        /// </summary>
        internal static string NotificationsNotFound {
            get {
                return ResourceManager.GetString("NotificationsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ был создан.
        /// </summary>
        internal static string OrderCreated {
            get {
                return ResourceManager.GetString("OrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ был найден.
        /// </summary>
        internal static string OrderFound {
            get {
                return ResourceManager.GetString("OrderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ не был найден.
        /// </summary>
        internal static string OrderNotFound {
            get {
                return ResourceManager.GetString("OrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы найдены.
        /// </summary>
        internal static string OrdersFound {
            get {
                return ResourceManager.GetString("OrdersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы не найдены.
        /// </summary>
        internal static string OrdersNotFound {
            get {
                return ResourceManager.GetString("OrdersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт не был создан.
        /// </summary>
        internal static string ProductNotCreated {
            get {
                return ResourceManager.GetString("ProductNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт не был найден.
        /// </summary>
        internal static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт не был удален.
        /// </summary>
        internal static string ProductNotRemoved {
            get {
                return ResourceManager.GetString("ProductNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт не был обновлен.
        /// </summary>
        internal static string ProductNotUpdated {
            get {
                return ResourceManager.GetString("ProductNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На складе нет нужного количества продуктов.
        /// </summary>
        internal static string ProductsNotEnough {
            get {
                return ResourceManager.GetString("ProductsNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукты не были найдены.
        /// </summary>
        internal static string ProductsNotFound {
            get {
                return ResourceManager.GetString("ProductsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица продукта не была добавлена.
        /// </summary>
        internal static string ProductUnitNotCreated {
            get {
                return ResourceManager.GetString("ProductUnitNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица продукта не была найдена.
        /// </summary>
        internal static string ProductUnitNotFound {
            get {
                return ResourceManager.GetString("ProductUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица продукта не была удалена.
        /// </summary>
        internal static string ProductUnitNotRemoved {
            get {
                return ResourceManager.GetString("ProductUnitNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единица продукта не была обновлена.
        /// </summary>
        internal static string ProductUnitNotUpdated {
            get {
                return ResourceManager.GetString("ProductUnitNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единицы продукта не были добавлены.
        /// </summary>
        internal static string ProductUnitsNotCreated {
            get {
                return ResourceManager.GetString("ProductUnitsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единицы продукта не были найдены.
        /// </summary>
        internal static string ProductUnitsNotFound {
            get {
                return ResourceManager.GetString("ProductUnitsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единицы продукта не были обновлены.
        /// </summary>
        internal static string ProductUnitsNotUpdated {
            get {
                return ResourceManager.GetString("ProductUnitsNotUpdated", resourceCulture);
            }
        }
    }
}
